---
# Repository configuration for wetransform managed repositories

# Reference presets that should apply to this repository
presets:
  - renovate # renovate workflow
  - renovate-config # managed renovate config
